name: Generate ASCII Artwork

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR" >> dragon.txt    

        - name: Test Files
          run: grep -i "dragon" dragon.txt
          
        - name: List repo Files
          run: ls -ltra