name: Exploring workflow filters and activities

on:
    workflow_dispatch: 
    push:
#      branches-ignore:
#        - feature/* # feature/add-music, feature/updateImages
#        - test/**  #  test/ui/index, test/checkout/payment/
     branches: 
        - main
        - '!feature/*'  #ignoring pushing to any branch name starting with feature using !
    pull_request:
      types:
        - opened
        - closed
      paths-ignore:
        - README.md  # workflow will only run when a pull request that inclueds a change on an any file other than README.md
      branches: 
        - main    # configures your workflow to only run on pull request that target specific branches
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{github.event_name}}